# name: Deploy GCP VM with Terraform

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v3
#       with:
#         terraform_version: 1.5.0


#     - name: Terraform Init
#       run: terraform init
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

#     - name: Terraform Plan
#       run: terraform plan
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

#   approval-apply:
#     runs-on: ubuntu-latest
#     needs: deploy
#     environment:
#         name: prod

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v3
#       with:
#         terraform_version: 1.5.0


#     - name: Terraform Init
#       run: terraform init
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

#     - name: Terraform Apply
#       run: terraform apply -auto-approve
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
